// export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const DISPLAY_ALERT = "TOGGLE_SIDEBAR";
export const CLEAR_ALERT = "CLEAR_ALERTR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_REPORT_BEGIN = "CREATE_REPORT_BEGIN";
export const CREATE_REPORT_SUCCESS = "CREATE_REPORT_SUCCESS";
export const CREATE_REPORT_ERROR = "CREATE_REPORT_ERROR ";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN ";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS ";
